---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
      filters:
        - ansible.eda.dashes_to_underscores:
  rules:
    - name: Process Gitea push event
      condition: event.meta.headers.X_Gitea_Event == "push"
      action:
        run_job_template:
          post_events: true
          name: roger_that 
          organization: Default
          job_args:
            extra_vars:
              user_detail: "{{ event.payload.head_commit.message | replace('\n', ' ') | trim }}"

